### ISSUE TITLE
Non-English characters are not represented properly

### ISSUE THREAD

**Issue by edjacob25** [kennycason/kumo#12]
Characters commonly used in languages like Spanish or French are not stored nor shown properly because the use of a deprecated method in IOUtils.
The fix is rather simple, just change the following line from `nlp/FrequencyAnalizer.java`:
```java
public List<WordFrequency> load(InputStream fileInputStream) throws IOException {
        return load(IOUtils.readLines(fileInputStream));
    }
}
```
to
```java
public List<WordFrequency> load(InputStream fileInputStream) throws IOException {
        return load(IOUtils.readLines(fileInputStream,"utf-8"));
    }
```
or add an overload method which let you choose your encoding.

**Comment by kennycason** [comment]
thanks! I'll update it and make it configurable, utf8 by default :)

**Comment by kennycason** [comment]
Making a lot of other configuration updates as well.

**Comment by kennycason** [comment]
I will be doing a re-release tomorrow after more testing/refactoring.
