### ISSUE TITLE
Empty string appear in word frequency list causing exception

### ISSUE THREAD

**Issue by RCasatta** [kennycason/kumo#14]
Hi,
I am hitting this exception:

java.lang.IllegalArgumentException: Width (0) and height (25) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:340)
	at wordcloud.Word.<init>(Word.java:39)
	at wordcloud.WordCloud.buildWord(WordCloud.java:260)
	at wordcloud.WordCloud.buildwords(WordCloud.java:247)
	at wordcloud.WordCloud.build(WordCloud.java:107)

I've the empty string in the stop word set and also a minimum length of 3 but apparently the empty string is in the word frequency list. Need to remove that entry by hand from the list

**Comment by kennycason** [comment]
Thanks for the report! I'll fix this.

**Comment by wolfposd** [comment]
in WordCloud.java #246 its possible to add an additional check for empty strings:

```java
    protected List<Word> buildwords(final List<WordFrequency> wordFrequencies, final ColorPalette colorPalette) {
        final int maxFrequency = maxFrequency(wordFrequencies);

        final List<Word> words = new ArrayList<>();
        for(final WordFrequency wordFrequency : wordFrequencies) {
            if(!wordFrequency.getWord().isEmpty()) { // Add this check to avoid IllegalArgumentException
                words.add(buildWord(wordFrequency, maxFrequency, colorPalette));
            }
        }
        return words;
    }
```

**Comment by kennycason** [comment]
:+1: Agreed. Sounds like a combination of bad tokenization/normalization/usage. I'll add a check.

**Comment by kennycason** [comment]
should be fixed now.
