### ISSUE TITLE
Unrecognizable Chinese characters on output image

### ISSUE THREAD

**Issue by georgeguo** [kennycason/kumo#22]
Hi,

When I was trying to produce a wordcloud based on a chinese txt file, the output image only contains blocks instead of correct Chinese words.

I've tried to encode the input file into "UTF-8" and "GBK". Both of the encoding couldn't fix the problem.

I'm using the sample code from the Github page with Kumo-1.4.jar to produce Chinese circle wordcloud through Eclipse.

Here is my code piece:

```
 public static void chineseCloud() {
    try {
        final FrequencyAnalizer frequencyAnalizer = new FrequencyAnalizer();
        frequencyAnalizer.setWordFrequencesToReturn(600);
        frequencyAnalizer.setMinWordLength(2);
        frequencyAnalizer.setWordTokenizer(new ChineseWordTokenizer());

        File initialFile = new File("D:/Clavis/TopicMining/Dataset/chinese.txt");
        final List<WordFrequency> wordFrequencies = frequencyAnalizer.load(new FileInputStream(initialFile));
        final WordCloud wordCloud = new WordCloud(600, 600, CollisionMode.PIXEL_PERFECT);

        wordCloud.setPadding(2);
        wordCloud.setBackground(new CircleBackground(300));
        wordCloud.setColorPalette(new ColorPalette(new Color(0xD5CFFA), new Color(0xBBB1FA), new Color(0x9A8CF5),
                new Color(0x806EF5)));
        wordCloud.setFontScalar(new SqrtFontScalar(12, 45));
        wordCloud.build(wordFrequencies);
        wordCloud.writeToFile("D:/Clavis/TopicMining/Dataset/chinese_language_circle.jpg");
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

Thanks,

George

**Comment by kennycason** [comment]
@georgeguo Thanks for filing the bug. What operating system are you using?

**Comment by georgeguo** [comment]
@kennycason Sorry for the late reply. This code was running on Windows 10. I haven't tried on Mac yet. Do you think it is my code's problem or the OS?

**Comment by kennycason** [comment]
my guess is an OS issue or encoding issue with the file. i need to also ensure my loader is reading in UTF8 and I need to make that configurable. I'll look into it some more. :)

**Comment by jayyuz** [comment]
u can try this
 `wordCloud.setKumoFont(new KumoFont("宋体", FontWeight.PLAIN));`
Remember to add [the font file](http://file3.data.weipan.cn.wscdns.com/77097705/941f76fdcccfd5930091367722eccd35b7339600? Ip=1501335167112.95.2.189&ssig=Z7PuYYZqiZ&Expires=1501335767&KID=sae, l30zoo1wmz&fn=simsun.ttc&skiprd=2&se_ip_debug=112.95.2.189&corp=2& from=1221134) to _/jre/lib/fonts_
