### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by theooos** [kennycason/kumo#34]
I've been trying to implement this myself to help you out, but have been struggling. Emoji support would be great, have been attempting to create a word cloud of all my conversations with my other half, to be printed on a canvas. We use emojis a lot, and to see their frequency turn up too would be great.

**Comment by kennycason** [comment]
Interesting. I love this idea. :) Let me think on it a bit.

**Comment by kennycason** [comment]
Progress :)
![screen shot 2016-06-14 at 2 37 54 pm](https://cloud.githubusercontent.com/assets/2858428/16060649/b97d646c-323d-11e6-9169-5fcff3e7737c.png)

**Comment by kennycason** [comment]
![wordcloud_emoji](https://cloud.githubusercontent.com/assets/2858428/16062303/20475c44-3247-11e6-8f8c-bc99b25fe2de.png)

**Comment by kennycason** [comment]
Added support for loading TTF files. 
Fixed bug in text placement so that text/emoji's don't get cut off.

**Comment by kennycason** [comment]
Here is an example. Having a TTF that supports emoji is also key. https://github.com/kennycason/kumo/blob/master/src/test/java/com/kennycason/kumo/EmojiWordCloudITest.java

**Comment by kennycason** [comment]
I just deployed Kumo 1.8

**Comment by theooos** [comment]
Legend!

**Comment by theooos** [comment]
Tried using OpenSansEmoji as you did, but a couple of Emojis get mis-translated along the way as pictured. Also, I'd really love to use apple's default emojis with the Apple Color Emoji font, however this just returns a blank image.

And just to really push my luck, I can imagine this could require quite a fair bit of extra work and I'd love to help out where I can, but could these emojis avoid the colour scheme and just use their default colour? Trying to read into the project and sort it myself so I'm not pestering you, but if you could point me in the right direction that'd be great!
![screen shot 2016-06-15 at 13 39 37](https://cloud.githubusercontent.com/assets/5040901/16083666/bdea5390-330d-11e6-894a-62c91de4b371.png)
