### ISSUE TITLE
Wrong code in examples

### ISSUE THREAD

**Issue by liar666** [kennycason/kumo#42]
- In example 3:
`buildRandomColorPalette()` is not defined

- In example 4: according to
https://github.com/kennycason/kumo/blob/master/src/main/java/com/kennycason/kumo/palette/LinearGradientColorPalette.java
constructor of `LinearGradientColorPalette()` has colors first, then steps...

**Comment by kennycason** [comment]
👍 Indeed they are out of date. Thanks.

**Comment by hdiwan** [comment]
From com.kennycason.kumo.examples.WordCloudITest:

    private static ColorPalette buildRandomColorPalette(final int n) {                                                                                                                                                                                               
            final Color[] colors = new Color[n];
            for (int i = 0; i < colors.length; i++) {
                colors[i] = new Color(RANDOM.nextInt(230) + 25, RANDOM.nextInt(230) + 25, RANDOM.nextInt(230) + 25);
            }
            return new ColorPalette(colors);
       }
