### ISSUE TITLE
Lighten external dependencies.

### ISSUE THREAD

**Issue by kennycason** [kennycason/kumo#43]

**Comment by rzo1** [comment]
Please think about removing `lambdaj` as this drags some odd dependencies (i.e. `hamcrest`) into the code base.

**Comment by kennycason** [comment]
@rzo1 definitely agree. As of late I have been using Eclipse Collections for everything, but will try and stick to only using Java libs as much as possible.

**Comment by rzo1** [comment]
I worked on this in my forked repo (and did some heavy refactoring to extract some concepts in different maven modules). Maybe this is interesting and I can submit a pull request?

**Comment by kennycason** [comment]
yeah sounds great. don't refactor the chinese tokenizer yet however, I'll pull that out next and move it into a different project kumo-tokenizers-chinese, or something.

**Comment by howtimeflies-io** [comment]
Hi @rzo1 and @kennycason 

Is there any progress in removing `lambdaj`?
I am going to do it myself if you did not start it yet.

Thanks.

**Comment by rzo1** [comment]
@howtimeflies-io I just added the pull request... did this 2 months ago... ;)

**Comment by howtimeflies-io** [comment]
Thank you @rzo1 

I did it myself just now 😄 
 
Maybe it is also nice to update the maven dependencies (`commons-io`, `commons-lang3` and `junit`) to their latest version in your pull request.

**Comment by rzo1** [comment]
I think, I did an update on the dependencies in my other branch (extracting the heavy nlp dependencies) @howtimeflies-io

**Comment by howtimeflies-io** [comment]
@rzo1 

Cool! I will check that branch. Thanks.

**Comment by kennycason** [comment]
Thanks guys! I just reviewed the PRs, some minor comments and I'll test and merge!

**Comment by rzo1** [comment]
@kennycason If I can support updating documentation and/or changelog, just comment here with concrete tasks, so we can go for Maven Central soon :)

**Comment by kennycason** [comment]
@rzo1 I'm planning on updating doc, testing, and deploying to maven central tomorrow afternoon. I am baby sitting some large hadoop jobs so have a bit of "free" during the afternoon. :)

**Comment by kennycason** [comment]
I noticed the project doesn't even compile. Gong to resolve that before anything.

**Comment by kennycason** [comment]
@rzo1 Did you run any of the examples after you made this refactor? Mine are all stuck in infinite loops, or run out of heap space, and such. Logging is also not printing out anymore. 

I'm going to debug through it and see what the issue is.

**Comment by rzo1** [comment]
Maybe we can meet on IRC to discuss on demand finding? ;)

**Comment by kennycason** [comment]
@rzo1 it's no problem. Given the lack of unit tests and size of refactor, I'm not surprised, nor concerned ha.
Learnings so far:
- sort got reversed on the frequency loader. fixing that and adding unit test
- next the image rotator is killing the heap, not sure why, investigating now. :)

**Comment by kennycason** [comment]
Of course, by lack of unit tests, I mean, MY lack of unit tests :D

**Comment by kennycason** [comment]
it's trying to create an array of size 12,468x4070 in CollisionRaster for each word, when this is supposed to just be the size of the canvas. Not sure why yet, but that certainly explains the heap space exceptions

**Comment by rzo1** [comment]
I was expecting, that I may break something - can you tell me the name of the test-case? So I can start some investigations, too ? I am IRC available at freenode / #kumo
