### ISSUE TITLE
Version 1.10 Maven Central probabily broken?

### ISSUE THREAD

**Issue by rzo1** [kennycason/kumo#48]
Hi @kennycason ,

just recognized, that you released `1.10`.

However, I think, that this release on mvn-central is broken.

I cannot find the "father-pom" for 1.9 / 1.10: http://repo1.maven.org/maven2/com/kennycason/kumo/

Modules are available in 1.9 and 1.10: http://repo1.maven.org/maven2/com/kennycason/

Maybe you can take a look at it :) - for now, it is not useable via mvn central and one have to install it locally.

**Comment by kennycason** [comment]
oh crap. Thanks! I'll get this fixed asap.

**Comment by kennycason** [comment]
@rzo1 Appears to be updated. I checked both directories you linked to.

**Comment by rzo1** [comment]
seems to be available now, but i will check in 1-2 days until the mvn repos are synced

**Comment by rzo1** [comment]
ok, i integrated `1.11` which worked via Maven Central.
