### ISSUE TITLE
Help on your code

### ISSUE THREAD

**Issue by glorieux-f** [kennycason/kumo#50]
Hi Kenny,

I’m working in NLP for French https://github.com/oeuvres/Alix
I’m providing WordClouds with morpho-syntactic infos (nouns, names, verbs…).
http://obvil.lip6.fr/alix/wordcloud.jsp?bibcode=hugo_miserables&frantext=on
This javascript lib provide a nice result, but is client side and do not allow caching.
I have started a java implementation with an HTML output.
https://github.com/oeuvres/Alix/blob/master/java/alix/viz/Cloud.java 
Your result is far more nicer but your code do more than I need.
HTML rendering will not be pixel perfect compared to PNG but offers other advantages.
An HTML renderer needs only the collision result as a tuple (x, y, angle).

I will try to understand your code and find the central core, all your advice is welcome.

**Comment by kennycason** [comment]
For clientside word clouds I recommend checking out: https://github.com/jasondavies/d3-cloud
Our company uses this for our client facing word clouds as well. :)

Let me know all the issues you run into or things that Kumo can't do, feature wise, as I'd likely be interested in adding them to kumo as well.

**Comment by glorieux-f** [comment]
Hi Kenny,

Sorry to have miss your comment, I was busy on other tasks.
I will recheck jasondavies. I’m afraid of Javascript freeze on client  because I want to display dozens of wordclouds as search results in a bibliographic base.
I will give you news here when I will have found my solution, thanks for advice.
