### ISSUE TITLE
Image to Word Cloud Issue

### ISSUE THREAD

**Issue by RedNoo** [kennycason/kumo#53]
Hello,

I am trying to convert an image to word-cloud (like your whale.png).
But I am getting the following result. What can be the problem? 
![beautiful](https://user-images.githubusercontent.com/527050/30435368-4510f128-9972-11e7-95c8-5ad79fb7673d.png)
![result](https://user-images.githubusercontent.com/527050/30435389-50bf0cbc-9972-11e7-8413-d10d9b4e4c74.png)
Best
Onder

**Comment by Donnerbart** [comment]
The image will most probably have no alpha channel (there are no transparent pixels, so the word cloud is generated on the whole image).

**Comment by kennycason** [comment]
@Donnerbart Is correct. If you open the image in another tab, you'll see the background is actually white, and not transparent. :)
