### ISSUE TITLE
set log4j binding to scope=test

### ISSUE THREAD

**Issue by FunThomas424242** [kennycason/kumo#62]
Hello,
the usage of slf4j is nice to make a logger agnostic software. But the binding of log4j destroyed the agnostic. 

Please set the scope of log4j bindings to "test".  I have done this for you at pull request #61.

(Very thanks for your nice software)

**Comment by kennycason** [comment]
good catch. I will do that! thanks for noticing and commenting.

**Comment by kennycason** [comment]
Thanks for the pr! Merged in. I'll do a version bump + release soon.
