### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [kennycason/kumo#63]
Greetings, 

I'm a graphic designer and I would be more than happy to contribute to your project by creating a logo for it, let me know if you are interested.

Best regards.

**Comment by michaelizer** [comment]
I'd like to ask some questions before starting, your answers will help me to deliver a better product.

- What's the name that should be displayed on the logo?, If there should be any.
- How would you describe this project and What is it intended to do?
- What would you like this logo to transmit?

I'll look forward to your reply, kind regards.

**Comment by michaelizer** [comment]
What do you think of these?
![api](https://user-images.githubusercontent.com/35619342/41385977-e104f524-6f4c-11e8-9d62-dfcc02c8f011.png)

**Comment by kennycason** [comment]
@michaelizer Thanks! I think I like the bottom left, without the trailing circles. I like that its is slightly of center. The off center nature of it for some reason even made me thing of the cloud being "alive", like having eyes or what not haha. 

Which one do you like?

**Comment by michaelizer** [comment]
I liked both of the bottom, if you liked the left one I'll upload the files through a pull request. What do you say?

**Comment by kennycason** [comment]
Sounds great. We should probably make a transparent background version as well.

**Comment by michaelizer** [comment]
@kennycason Done! ([#65](https://github.com/kennycason/kumo/pull/65)), also uploaded the files on Google Drive adding the .svg, .pdf and other files for you to have full control of your logo.

**Comment by kennycason** [comment]
merged. :) Thanks again!
