### ISSUE TITLE
Feature Request: Scale/Resize background images to WordCloud dimensions

### ISSUE THREAD

**Issue by joergrech** [kennycason/kumo#64]
I would like to use an image as a background on a wordcloud of different sizes / dimensions without creating an individual image for each size. 

For example, I would like to use the whale.png image with 990x618 pixel on a Wordcloud with 4000x4000 pixel and need to scale the whale image roughly 4 times (in both dimensions to keep the proportions). 

I couldn't find a way to do this using the setBackground method or the PixelBoundryBackground Class. It would be great if you could implement a method to add a scale/resize factor or absolute dimensions.

**Comment by kennycason** [comment]
Hey! I know this was a __LONG__ time ago, but someone picked up the issue. Pending a few small requests i'll be merging this in. https://github.com/kennycason/kumo/pull/88

**Comment by kennycason** [comment]
work complete and merged
