### ISSUE TITLE
How to repeat word and auto fill the Mask Bitmap?

### ISSUE THREAD

**Issue by candrwow** [kennycason/kumo#87]
I have a few words and a big picture, the words do not repeat, can not fill mask, maybe manually add repeated word frequency is a solution, but in the API level is there a way to automatically fill?
Thank you for your work!

**Comment by kennycason** [comment]
@candrwow thanks a lot! It looks like someone also decided this was an issue and pushed up a PR. After some minor changes I'll merged and release a long overdue version bump.

**Comment by kennycason** [comment]
https://github.com/kennycason/kumo/pull/88

**Comment by kennycason** [comment]
work complete and merged
