### ISSUE TITLE
add support for users using java 9+ modules

### ISSUE THREAD

**Issue by danlangford** [kennycason/kumo#94]
# Request 
add support for users using Java 9+ jigsaw/JMPS modules. Currently when I use kumo in my moduled project i get an error.

# Error

```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules kumo.api and kumo.core export package com.kennycason.kumo.nlp.tokenizer to module commons.io
```

which was addressed here: https://stackoverflow.com/questions/46277188/modules-a-and-b-export-package-some-package-to-module-c-in-java-9

# Supporting Evidence

A couple of reasons I feel this would be a good idea for your project:
- java 14 added `jpackage` an official command to package up a java project with an OS native launcher
- `jpackage` is run after `jlink` which will link in (bundle) the needed pieces of the JRE creating a stand-alone, "native" application
- `jpackage` requires a project to be using modules
- Java 17 is an LTS and will be released in ~1 year and will include these technologies

so I think that in the future more people will be wanting to explore these new technologies and will be unable to use your library in its current state. 

I am currently writing some templates to show people how to use this technology and I have been using your library to create the initial non-module samples but I cannot move forward with this library.

# Easy Approach

the easy approach would just be to make all your maven modules to not overlap package names. And add `Automatic-Module-Name` in a _MANIFEST.MF_. in this approach you could stay on Java 8. To expound: maybe _kumo-api_ could appeand `.api` to the package and _kumo-core_ appeands `.core`. Or maybe you could add `api` and `core` furtcher up int he package like you currently do with `cli`. Like `com.kennycason.kumo.api.nlp.tokenizer` and  `com.kennycason.kumo.core.nlp.tokenizer` 

# More Involved Approach

You could also more fully adopt Java 9 or Java 11. If you did this you would have a choice to more fully support moduled projects by writing a _module-info.java_. If you didnt want to drop support for Java 8 then you could leverage the Multi-Release JAR pattern. 

However I would at least start with the easy approach first.

**Comment by danlangford** [comment]
I would be more than willing to assist by supplying a PR but wanted to see if you have put thought or work into it before I submit a PR that changes your package structure all around. As a fellow Java developer I understand that a package structure and project organization may have a very specific form that others may not fully appreciate at a glance.

**Comment by kennycason** [comment]
@danlangford good catch. Thanks! Checking the PR now!

**Comment by kennycason** [comment]
@danlangford extremely late, but finally merged in! thanks again! Note that i'll need to do a maven version bump and deploy. I'm going to do that now, barring no issues.
